### PR TITLE
Fix typo in English translation

### PR DESCRIPTION
**Pull request by TurnrDev**
Might need to be edited by yourself, it looked like a text file so I edited using github editor but the diff is saying -28 bytes.

I changed Shelder to Shelter

### CODE REVIEW

**Comment by floscher** [comment]
Unfortunately you can't simply edit `*.lang` files with the GitHub text editor. These files are binary files, which get mangled if you do.

The two bytes before each string are representing the length of the string directly following them. In theory you would be able to simply replace the `d` with a `t`, because the string length isn't changing. But the GitHub text editor strips all `0x00` bytes from the file when committing, so your edit shrinked the file from 389 bytes to 361 bytes and the file now won't be read correctly by JOSM.

@bwr57 fixed the typo in the `*.txt` files with https://github.com/bwr57/CustomizePublicTransportStop/commit/7c7dcc5a0ef777cbdba0dd3ba5d5f574c2aa5759#diff-0e21373ba308867eb1ba5198d599795bL23 , so it's probably just a matter of regenerating the `*.lang` files.

**Comment by bwr57** [comment]
Dear @JayTurnr. 
Thank you for the your bug report and fix. Really I fixed this orfographic error about one month ago. The main error wasn't in the file changed by you, but in the CustomizePublicTransportStopDialog.java file. Now it is line 37

private static final String SHELTER_CAPTION = "Shelter";

The en.txt file provide a translation of the labels from English language to other languages (now it are Russian and Spanish) by Tr class from the I18n namespace. And this file must be changed together with the java code only. In other cases the error will exists and at using other languages too. Now and the java and txt files are fixed. The en.lang file was recompiled too. For this target I wrote TransJosmStrings (https://github.com/bwr57/TransJosmStrings) utilite. But it is pre-alpha. So the both bugs are fixed in the last released jar-file. And English and Russian version must work. If you use the JOSM plugin repository for a download, than a translations to the other languages will not work. I can't upload the txt and lang files to the JOSM svn. I don't know why 
The pt_assistant version isn't fixed. I don't know, have I right for this or not.

Best regards
Rodion

**Comment by floscher** [comment]
Hi @bwr57, yes you fixed the typo in the Java source code and in the file `Text/en.txt` both in the GitHub repository and in the SVN. Nobody questioned that.

https://github.com/bwr57/CustomizePublicTransportStop/blob/f0919745b43437556db49405049e486be74704f5/Text/en.txt#L23
https://github.com/bwr57/CustomizePublicTransportStop/blob/f0919745b43437556db49405049e486be74704f5/src/org/openstreetmap/josm/plugins/customizepublictransportstop/CustomizePublicTransportStopDialog.java#L37

But still the currently published version of `CustomizePublicTransportStop` contains the string `Shelder` in the `en.lang` file. I checked both the version published in the SVN and the one published on GitHub.
The version published on GitHub displays `Shelter` in English and `Refugio` in Spanish, but according to `Text/es.txt` it should read `Techo`:
https://github.com/bwr57/CustomizePublicTransportStop/blob/f0919745b43437556db49405049e486be74704f5/Text/es.txt#L23
So JOSM does not correctly pick up the translations that are defined in this GitHub repo.
cpts

> The pt_assistant version isn't fixed.

That statement is not true:
pta

I think I know what goes wrong. And if you want my help, I could explain it in detail, so you can fix it in your plugin, too.

---

> I don't know, have I right for this or not.

You have every right to do this. Just to clarify: I honestly don't have any bad intentions against this project. If you are willing to maintaining this project, that's completely fine with me. The merger with `pt_assistant` was based on assumptions on my side. I apologized at https://github.com/bwr57/CustomizePublicTransportStop/issues/2#issuecomment-439715519 and commented at https://josm.openstreetmap.de/ticket/17005#comment:3 that probably the best option is to undo the merge, but that would come into effect at the earliest with the next release of `pt_assistant`.

**Comment by bwr57** [comment]
Dear @floscher, 
Thank you for the your message. I didn't copy the changed lang file into the new release. It's my mistake. I'm sorry. Today I coped the updated lang file into the jar-file and uploaded it into the repositories. I tested it in the Russian enviroment. All is OK. But in the Russian enviroment all was OK and early. It's possible, that the JOSM lang files contains a translation of the word "shelter" to Russian and the my mistake isn't perceptible in the Russian enviroment. It is possible, that the Spanish variant will not work. 

>>     The pt_assistant version isn't fixed.

> That statement is not true:

I'm sorry about my bad English. It's the bad translation. More properly is "I didn't fix this bug in the pt_assistant version. I don't know, have I right for this or not."

I'm sorry about delay with the answer about the pt_assistant plugin. I hadn't enought time to investigate this project. Trust me, I don't think, that you have a bad intentions. Simple it is a little unexpected. I didn't think that this project can to draw attention.

Am I right, when I think, that you are a JOSM developer? If yes, I want to give thanks to @don-vip and @stoecker for a fixing of the problems with a compability with the new versions of the JOSM. I saw this changes, but I didn't uploaded it into Github repository. I'm sorry. 

And i have the question. I can't download the lang files into the svn repository properly. Therefore, the half of the english words don't translate to Russian, if I download plugin by JOSM. If I copy the my jar  file to the AppData\Roaming\JOSM\plugins all is good. I don't think, that it is a big problem. The JOSM users in Russia know English. Who don't know use Poltach :) , but it isn't beutiful when a mixture of the English and Russian words is present. What is my error?

Thank you!


Best regards
Rodion

**Comment by floscher** [comment]
> Am I right, when I think, that you are a JOSM developer?

@bwr57 I am a developer for some JOSM plugins, not so much JOSM core. But I also created a Gradle plugin to help build JOSM plugins, therefore I am rather familiar with how these *.lang files work.

> I can't download the lang files into the svn repository properly. Therefore, the half of the english words don't translate to Russian, if I download plugin by JOSM.

One thing I noticed, is that some files in the SVN repository have a different file encoding (e.g. [/Text/ru.txt](https://trac.openstreetmap.org/browser/subversion/applications/editors/josm/plugins/CustomizePublicTransportStop/Text/ru.txt) seems to have a Windows file encoding instead of UTF-8). This might cause such problems.

**Comment by TurnrDev** [comment]
I'm gonna admit this is well above my head. I don't expect this to be merged as it's incorrect as a PR. I hope this issue gets solved though.

**Comment by bwr57** [comment]
Dear @floscher!

Thank you for the your support.

> some files in the SVN repository have a different file encoding (e.g. /Text/ru.txt seems to have a Windows file encoding instead of UTF-8).

 I changed the file encoding to the UTF-8 and recompiled ru.lang an es.lang. In the test enviroment the Spanish translation is properly now. But in the downloaded by Josm version a translation is not working as early.

es interface

The original problem with the word "shelter" is exists. I can't understand why, but JOSM don't show a translation of this word properly. I hacked it by a replace of the word "Shelter" on to "Shelter " with a space character in the end in the Java code and txt and lang files. Now all are OK, but a cause of this situation isn't clear for me. It's possible, that a cause is bug in the tr class.

Best regards 
Rodion

**Comment by floscher** [comment]
@bwr57 The problem is probably that JOSM core also uses `tr("Shelter")`, but more in the sense of a emergency shelter or homeless shelter than a shelter of a public transport stop.
That's why `"refugio"` keeps popping up as Spanish translation of `"Shelter"`.

My recommendation for solving this would be to use `trc("public transport stop", "Shelter")`, which means "shelter in the context of a public transport stop". That way JOSM knows to use the translation for "Shelter" that has the context "public transport stop".

This would make the `en.lang` file a bit more complicated, the shelter entry would then become like this:
`"public transport stop\u0004Shelter"`
(`\u0004` is one byte of value `0x04`, JOSM will ignore everything up to and including that byte)

The corresponding entry in `es.lang` would remain the same as before:
`"Techo"`

**Comment by bwr57** [comment]
Dear Mr. @floscher!
Thank you! 
This method is working. But there is one correction. Josm use as separator not chr(4), but chr(10). And a name of the context section must began from a substring "_:". It's very originally, I think.
For any case I corrected en.txt, en.lang and es.lang files and the java code and also the TransJosmStrings project to take in account this features.
I'll include a changed version of the lang files into the next release.
Thank you again!
Best regards
Rodion

**Comment by floscher** [comment]
Ah yes, sorry, I confused the format of JOSM's *.lang files with the format of *.mo files used by gettext.

You are right, JOSM uses a prefix `_:`, then the context, then the line feed character (`0x0a` = 10), then the string itself. Seems like I looked in the wrong file when writing my last comment.

Great that it works now!

**Pull request closed without merging**
